"""add cascade deletes and indexes

Revision ID: 398a0ac85112
Revises: 295e54d9b61f
Create Date: 2026-06-09 16:33:06.790558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398a0ac85112'
down_revision: Union[str, Sequence[str], None] = '295e54d9b61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)
    op.drop_constraint(op.f('playlists_user_id_fkey'), 'playlists', type_='foreignkey')
    op.create_foreign_key(None, 'playlists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_songs_playlist_id'), 'songs', ['playlist_id'], unique=False)
    op.drop_constraint(op.f('songs_playlist_id_fkey'), 'songs', type_='foreignkey')
    op.create_foreign_key(None, 'songs', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.create_foreign_key(op.f('songs_playlist_id_fkey'), 'songs', 'playlists', ['playlist_id'], ['id'])
    op.drop_index(op.f('ix_songs_playlist_id'), table_name='songs')
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.create_foreign_key(op.f('playlists_user_id_fkey'), 'playlists', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    # ### end Alembic commands ###
