"""add artist, duration_ms, image_url to songs

Revision ID: 8f213b3b41eb
Revises: 481c359d803e
Create Date: 2026-06-13 12:41:31.063385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f213b3b41eb'
down_revision: Union[str, Sequence[str], None] = '481c359d803e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist', sa.String(length=255), nullable=False))
    op.add_column('songs', sa.Column('duration_ms', sa.Integer(), nullable=False))
    op.add_column('songs', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'image_url')
    op.drop_column('songs', 'duration_ms')
    op.drop_column('songs', 'artist')
    # ### end Alembic commands ###
